name: chatty
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  intl: ^0.20.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.5.3
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.4.0
  http: ^1.4.0
  cryptography: ^2.5.0
  flutter_secure_storage: ^9.0.0
  convert: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-Light.ttf
        weight: 300
