// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Aq_6LlKEcrG2QpZjXD3ye6rDNUi233I',
    appId: '1:431304368414:web:95338efb832872f05a290f',
    messagingSenderId: '431304368414',
    projectId: 'cns-project-f0d24',
    authDomain: 'cns-project-f0d24.firebaseapp.com',
    storageBucket: 'cns-project-f0d24.firebasestorage.app',
    measurementId: 'G-XGZ8X5DWD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChYeqa0hKMQne-xe1RFORriNKM22jAiGg',
    appId: '1:431304368414:android:86acc5d07dde4e555a290f',
    messagingSenderId: '431304368414',
    projectId: 'cns-project-f0d24',
    storageBucket: 'cns-project-f0d24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCin2PvmpTxRhm5G2J_X7rZ_plA2RyMXN8',
    appId: '1:431304368414:ios:59361c4b3df99b315a290f',
    messagingSenderId: '431304368414',
    projectId: 'cns-project-f0d24',
    storageBucket: 'cns-project-f0d24.firebasestorage.app',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCin2PvmpTxRhm5G2J_X7rZ_plA2RyMXN8',
    appId: '1:431304368414:ios:59361c4b3df99b315a290f',
    messagingSenderId: '431304368414',
    projectId: 'cns-project-f0d24',
    storageBucket: 'cns-project-f0d24.firebasestorage.app',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3Aq_6LlKEcrG2QpZjXD3ye6rDNUi233I',
    appId: '1:431304368414:web:229d7e6afe4dbf865a290f',
    messagingSenderId: '431304368414',
    projectId: 'cns-project-f0d24',
    authDomain: 'cns-project-f0d24.firebaseapp.com',
    storageBucket: 'cns-project-f0d24.firebasestorage.app',
    measurementId: 'G-G49W937B2G',
  );
}
